# This file will compile every lesson in ../FractalTree.Lessons and write them to ../FractalTree.Frontend/public/CompiledLessons
import os
import mklesson

def main():
    lessonsPath = "../FractalTree.Lessons"

    root, dirs, files = os.walk(lessonsPath).__next__()
    
    importerFile = "// This File Was Generated By The Fractal Tree Lesson Compiler (mkall.py)\n\n"

    for dir in dirs:
        importerFile += mklesson.compile_lesson(os.path.join(lessonsPath, dir))

    importerFile += "\nwindow.doneInitStep()"

    f = open("../FractalTree.Frontend/public/CompiledLessons/importer.js", "w")
    f.write(importerFile)
    f.close()
    print("Done Writing")

if (__name__ == "__main__"):
    main()