
import os
import json

def splash_screen():
    print("-" * 28)
    print("Fractal Tree Lesson Compiler")
    print("-" * 28)

def compile_course_in_language(dir, lang):
    jsFile = ""
    courseInfoPath = os.path.join(dir, "course.json")

    with open(courseInfoPath, 'r') as file:
        courseInfo = json.load(file)
    
    courseID = "window.compiledCourse_" + courseInfo["id"] + "_" + lang
    jsFile += courseID + " = " + json.dumps(courseInfo) + ";\n\n" # Declare the course metadata
    jsFile += "window.lessonList.push(" + courseID +  ");\n\n" # Add the course to the global list

    return jsFile



def main():
    lessonPath = "../FractalTree.Lessons/python_intro"
    root, dirs, files = os.walk(lessonPath).__next__()
    
    jsFile = "// This File Was Generated By The Fractal Tree Lesson Compiler (mklesson.py)\n\n"

    for dir in dirs:
        print("Compiling Lesson For Language: " + dir + "\n")
        jsFile += compile_course_in_language(os.path.join(lessonPath, dir), dir)
        print("\n")

    print(jsFile)



if (__name__ == "__main__"):
    splash_screen()
    main()