// This File Was Generated By The Fractal Tree Lesson Compiler (mklesson.py)

window.compiledCourse_python_intro_ar = {"id": "python_intro", "lang": "ar", "name": "Intro To Python", "description": "Learn the very basics of Python 3, no prior coding knowledge required.", "icon": "Python.webp", "segments": []};

window.lessonList.push(window.compiledCourse_python_intro_ar);

window.compiledCourse_python_intro_en = {"id": "python_intro", "lang": "en", "name": "Intro To Python", "description": "Learn the very basics of Python 3, no prior coding knowledge required.", "icon": "Python.webp", "segments": ["# im nothing like yall", "# im something like yall"]};

window.lessonList.push(window.compiledCourse_python_intro_en);

