# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Compile Frontend And Lessons

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './FractalTree.Frontend'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache-dependency-path: 'FractalTree.Frontend/package-lock.json'
        cache: 'npm'
    - run: npm ci --force
    - run: npm run lessons
    - run: npm run build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
          commit-message: npm run build
          committer: Fractal Tree <194416362+TeamFractalTree@users.noreply.github.com>
          body: |
             Compiled the code in FractalTree.Frontend 🔥🔥🔥
          title: 'Compile New Build'
          branch: frontend-build-ci

